services:
  - type: web
    name: lovals
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/valentine-website-1.0.0.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
